export enum NotificationEventType {
  INVITED = 'INVITED',
  AGREED = 'AGREED',
  FUNDED = 'FUNDED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  INSPECTION_ENDING_SOON = 'INSPECTION_ENDING_SOON',
  RELEASED = 'RELEASED',
  DISPUTED = 'DISPUTED',
  RESOLVED = 'RESOLVED',
}
