export enum LedgerAccountType {
  USER_WALLET = 'USER_WALLET',
  ESCROW_HOLDING = 'ESCROW_HOLDING',
  PLATFORM_FEE_REVENUE = 'PLATFORM_FEE_REVENUE',
  PROVIDER_CLEARING = 'PROVIDER_CLEARING',
  TREASURY = 'TREASURY',
}
